apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
  labels:
    app: alloy

data:
  alloy.yaml: |
    livedebugging {
      enabled = true
    }
    
    discovery.kubernetes "pods" {
      role = "pod"
      selectors {
        role = "pod"
        label = "app=flog"
      }
    }
    
    loki.source.kubernetes "pods" {
      targets = discovery.kubernetes.pods.targets
      forward_to = [loki.write.vlinsert.receiver]
    }
    
    loki.write "vlinsert" {
      endpoint {
        url = "http://vlinsert.monitoring.svc.kubeyy.com:9481/insert/loki/api/v1/push"
      }
    }