apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      annotations:
        prometheus.vm/scrape: "true"
        prometheus.vm/port: "12345"
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      containers:
        - name: alloy
          image: registry.cn-hangzhou.aliyuncs.com/seam/alloy:v1.9.2
          args:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - --server.http.ui-path-prefix=/
            - --stability.level=generally-available
            - /etc/alloy/alloy.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
      nodeSelector:
          biz.type: victorialogs
      volumes:
        - name: config
          configMap:
            name: alloy-config