user root;
worker_processes 8;
worker_rlimit_nofile 262140;
worker_cpu_affinity auto;
error_log  logs/error.log;
#pid        run/nginx.pid;

events 
{
	use epoll;
	worker_connections  65535;
}


http 
{
	include       mime.types;
	default_type  application/octet-stream;
	
	sendfile        on;
	#aio on; 
    directio 512; 
    output_buffers 1 128k;
	log_not_found	off;
	keepalive_timeout  65;
	server_tokens off;
	
	gzip             on;
	gzip_comp_level  6;
	gzip_min_length  1k;
	gzip_buffers     4 8k;
	gzip_disable     "MSIE [1-6]\.(?!.*SV1)";
	gzip_types       text/plain application/x-javascript text/css application/xml text/javascript application/javascript application/json;
	
	log_format main '$remote_addr $upstream_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$request_time" "$upstream_response_time"';
	access_log logs/${server_name}.access.log main;
	access_log logs/http.access.log main;
	fastcgi_intercept_errors on;
	#error_page   500 502 503 504  /50x.html;

	server_names_hash_max_size 4096;
	resolver 8.8.8.8 114.114.114.114 valid=10s;

	server 
	{
		listen       80 default_server;
		server_name  _;
	
		location / 
		{
			proxy_pass http://$host;
        	proxy_set_header Host $host;
		}
	}

	server 
	{
		listen       80 ;
		server_name  hub.kbsonlong.com;

        location /https/ {
                resolver 8.8.8.8 114.114.114.114 valid=10s;
                add_header Access-Control-Allow-Origin *;
                set $upstream "";
                access_by_lua_block {
                    local uri = ngx.var.uri
                    local target_url = string.gsub(uri, "^/https/", "https://")
                    
                    ngx.log(ngx.INFO, "HTTPS proxy to: ", target_url)
                    ngx.var.upstream = target_url
                }
				proxy_ssl_verify_depth  2;
      		    proxy_ssl_session_reuse on;
    		    proxy_ssl_server_name      on;
                proxy_pass $upstream$is_args$args;
        }
        location /http/ {
                resolver 8.8.8.8 114.114.114.114 valid=10s;
                add_header Access-Control-Allow-Origin *;
                set $upstream "";
                access_by_lua_block {
                    local uri = ngx.var.uri
                    local target_url = string.gsub(uri, "^/http/", "http://")
                    
                    ngx.log(ngx.INFO, "HTTP proxy to: ", target_url)
                    ngx.var.upstream = target_url
                }
                proxy_pass $upstream$is_args$args;
        }
	}
	
	server
	{
		listen 28080;
		server_name _;
		access_log off;
		
		location /nginx_status 
		{
			stub_status on;
			access_log   off;
			allow 127.0.0.1;
			deny all;
		}
	}

}

stream {
    resolver 8.8.8.8 114.114.114.114 valid=10s;
    log_format basic '$remote_addr [$time_local] $protocol $status $bytes_sent $bytes_received $ssl_preread_server_name "$upstream_addr" $upstream_connect_time $server_addr $server_port';
    access_log logs/stream.access.log basic;

    server {
        listen 443;
        ssl_preread on;
        proxy_connect_timeout 5s;
        proxy_pass $ssl_preread_server_name:443;
    }

}