version: "3.8"
services:
  victoria-logs-hot:
    image: victoriametrics/victoria-logs:v1.44.0
    container_name: victoria-logs-hot
    ports:
      - "9428:9428"
    volumes:
      - ./data/vl7d:/data/vl
    command:
      - --envflag.enable
      - --http.shutdownDelay=15s
      - --httpListenAddr=:9428
      - --loggerFormat=json
      - --storageDataPath=/data/vl
      - --retentionPeriod=14d
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined

  victoria-logs-select:
    image: victoriametrics/victoria-logs:v1.44.0
    container_name: victoria-logs-select
    ports:
      - "9430:9430"
    command:
      - --storageNode=victoria-logs-hot:9428,victoria-logs-warn:9429
      - --httpListenAddr=:9430
    restart: unless-stopped
    depends_on:
      - victoria-logs-hot
      - victoria-logs-warn
    security_opt:
      - seccomp:unconfined
  victoria-logs-warn:
    image: victoriametrics/victoria-logs:v1.44.0
    container_name: victoria-logs-warn
    ports:
      - "9429:9429"
    volumes:
      - ./data/vl180d:/data/vl
    command:
      - --envflag.enable
      - --http.shutdownDelay=15s
      - --httpListenAddr=:9429
      - --loggerFormat=json
      - --storageDataPath=/data/vl
      - --retentionPeriod=180d
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined