discovery.relabel "pod_logs" {
    targets = discovery.kubelet.pods.targets

    rule {
    source_labels = ["__meta_kubernetes_pod_host_ip"]
    target_label = "host_ip"
    }
    rule {
    source_labels = ["__meta_kubernetes_pod_label_project_name"]
    target_label = "project_name"
    }
    rule {
    source_labels = ["__meta_kubernetes_pod_label_deploy_type"]
    target_label = "deploy_type"
    }
    rule {
    source_labels = ["__meta_kubernetes_pod_name"]
    target_label = "pod"
    }
    rule {
    source_labels = ["__meta_kubernetes_namespace"]
    target_label = "namespace"
    }
    rule {
    source_labels = ["__meta_kubernetes_pod_label_app"]
    target_label = "app"
    }
    rule {
    source_labels = ["__meta_kubernetes_pod_container_name"]
    target_label = "container"
    }
}

loki.source.kubernetes "pods" {
    targets = discovery.relabel.pod_logs.output
    forward_to = [otelcol.receiver.loki.default.receiver]
}

    otelcol.receiver.loki "default" {
        output {
        logs = [otelcol.processor.transform.default.input]
        }
    }

    otelcol.processor.transform "default" {
        error_mode = "ignore"
        log_statements {
        context = "log"
        statements = [
            "merge_maps(attributes, ParseJSON(body), \"insert\") where attributes[\"container\"] == \"istio-proxy\"",
            "set(body, attributes[\"response_code\"]) where attributes[\"container\"] == \"istio-proxy\" and (attributes[\"response_code\"] != nil or attributes[\"method\"] != nil)",
        "set(cache, ExtractPatterns(body, \"(?P<json>\\\\{.*\\\\})\")) where attributes[\"container\"] == \"node-cache\" and IsString(body)",
        "set(cache, ParseJSON(cache[\"json\"])) where attributes[\"container\"] == \"node-cache\" and cache[\"json\"] != nil",
        "merge_maps(attributes, cache, \"insert\") where attributes[\"container\"] == \"node-cache\" and IsMap(cache)",
        "set(body, cache) where attributes[\"container\"] == \"node-cache\" and IsMap(cache)",
        "set(cache, ExtractPatterns(body, \"^(?P<remote>\\\\[?[0-9A-Fa-f:.]+\\\\]?):(?P<port>\\\\d+)\\\\s+-\\\\s+(?P<id>\\\\d+)\\\\s+\\\\\\\"(?P<type>\\\\w+)\\\\s+(?P<class>\\\\w+)\\\\s+(?P<name>[^\\\\\\\"]+)\\\\s+(?P<proto>\\\\w+)\\\\s+(?P<size>\\\\d+)\\\\s+(?P<do>\\\\w+)\\\\s+(?P<bufsize>\\\\d+)\\\\\\\"\\\\s+(?P<rcode>\\\\w+)\\\\s+(?P<rflags>[A-Za-z,]+)\\\\s+(?P<rsize>\\\\d+)\\\\s+(?P<duration>[\\\\d\\\\.]+)s$\")) where attributes[\"container\"] == \"node-cache\" and IsString(body)",
            "merge_maps(attributes, cache, \"insert\") where attributes[\"container\"] == \"node-cache\" and IsMap(cache)",
            "set(body, cache) where attributes[\"container\"] == \"node-cache\" and IsMap(cache)",
        ]
        }
        output {
        logs = [otelcol.processor.batch.default.input]
        }
    }

    otelcol.processor.batch "default" {
        send_batch_size     = 1024
        send_batch_max_size = 2048
        timeout             = "5s"

        output {
        logs = [otelcol.exporter.otlphttp.default.input]
        }
    }

otelcol.exporter.otlphttp "default" {
    client {
    endpoint    = "{{ .Values.vlogEndpoint }}"
    timeout     = "30s"
    compression = "gzip"
    headers     = {
        "content-type"     = "application/x-protobuf",
        "VL-Extra-Fields"  = "cluster={{ .Values.clusterName }}",
        "VL-Stream-Fields" = "cluster,project_name",
        "VL-Ignore-Fields" = "loki.attribute.labels,job,instance",
    }
    }
}
